#!/usr/bin/env ruby

#
# Create symlinks from dotfiles -> home directory
#
# for example:
#
# dotfiles/vimrc -> ~/.vimrc
#

root = File.expand_path(File.dirname(__FILE__))
dotfiles_path = File.join(root, "dotfiles")

files = `ls #{dotfiles_path}`.split - [".", ".."]

files.each do |file|
  system("ln -sf '#{dotfiles_path}/#{file}' ~/.#{file}")
end
