#!/usr/bin/env ruby

#
# Create symlinks from files -> home directory
#
# for example:
#
# files/vimrc -> ~/.vimrc
#

root = File.expand_path(File.dirname(__FILE__))
dotfiles_path = File.join(root, "files")

files = `ls #{dotfiles_path}`.split - [".", ".."]

files.each do |file|
  system("ln -sf '#{dotfiles_path}/#{file}' ~/.#{file}")
end

system("ln -sf '#{root}/bin' ~/bin")
