export EDITOR="vim"

HISTSIZE=5000               # How many lines of history to keep in memory
HISTFILE=~/.zsh_history     # Where to save history to disk
SAVEHIST=5000               # Number of history entries to save to disk
HISTDUP=erase               # Erase duplicates in the history file

setopt appendhistory     # Append history to the history file (no overwriting)
setopt sharehistory      # Share history across terminals
setopt incappendhistory  # Immediately append to the history file, not just when a term is killed

source ~/.prompt
source ~/.aliases

if [ -d ~/.kerl ]; then
  source ~/.kerl/installs/18.3/activate
  test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"
  kiex use 1.5 > /dev/null
fi

if [ -d $HOME/bin ]; then
  export PATH=$PATH:$HOME/bin
fi

if [ -d $HOME/.gem/ruby/2.3.0 ]; then
  export PATH=$PATH:$HOME/.gem/ruby/2.3.0/bin
fi

export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
export PATH=$GOROOT/bin:$PATH
export PATH="$PATH:/opt/istio-1.0.3/bin"
export GO111MODULE=on

export GPG_TTY=$(tty)

if [ -e ~/.gnupg/S.gpg-agent ]
then
  exit
else
  pkill gpg-agent
  rm -f ~/.gpg-agent.env
fi

env=`gpg-agent --daemon --enable-ssh-support`
if [ $?==0 ]
then
  echo "$env" > ~/.gpg-agent.env
fi

bindkey '^r' history-incremental-search-backward
test -e /home/vagrant/.iterm2_shell_integration.zsh && source /home/vagrant/.iterm2_shell_integration.zsh || true

alias vim=nvim
